baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "Мой Блог"

# paginate = 1 # раскоментируй для проверки пагинации, это сделает 1 пост на страницу

[taxonomies]
  blog_category = "blog_categories"
  case_category = "case_categories"

