baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "Мой Блог"

[params]
  blogs_paginate = 6
  cases_paginate = 4

[taxonomies]
  blog_category = "blog_categories"
  case_category = "case_categories"

