baseURL = "https://thelazybison.com/"
languageCode = "en-us"

[params]
  blogs_paginate = 4
  cases_paginate = 4
  summaryLength = 50
  description = 'Specializing in Ruby on Rails development, The Lazy Bison offers fast, reliable, and scalable solutions for start-ups and SMEs in various industries.'
  keywords = 'Ruby on Rails, Hotwire, ReactJS, Development, Start-ups, SMEs, Legal services, eCommerce, Healthcare, Real Estate, Fintech, Veterinary, Crowdfunding'
  author = 'Lazy Bison'

[permalinks]
  case_categories = "/cases/:slug"
  blog_categories = "/blog/:slug"

[taxonomies]
  blog_category = "blog_categories"
  case_category = "case_categories"

[[menu.main]]
    identifier = "services"
    name = "services"
    url = "/#services"
    weight = 1

[[menu.main]]
    identifier = "explore"
    name = "explore"
    url = "/#explore"
    weight = 2

[[menu.main]]
    identifier = "blog"
    name = "blog"
    url = "/blog"
    weight = 3

[[menu.main]]
    identifier = "cases"
    name = "cases"
    url = "/cases"
    weight = 4

[[menu.main]]
    identifier = "testimonials"
    name = "testimonials"
    url = "/#testimonials"
    weight = 5


[related]
  includeNewer = false
  threshold = 80
  toLower = false
[[related.indices]]
    applyFilter = false
    cardinalityThreshold = 0
    name = 'keywords'
    pattern = ''
    toLower = false
    type = 'basic'
    weight = 100
[[related.indices]]
    applyFilter = false
    cardinalityThreshold = 0
    name = 'date'
    pattern = ''
    toLower = false
    type = 'basic'
    weight = 10
[[related.indices]]
    applyFilter = false
    cardinalityThreshold = 0
    name = 'blog_categories'
    pattern = ''
    toLower = false
    type = 'basic'
    weight = 70